// <auto-generated />
namespace preguntados_ppodgaiz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migracion_inicial_usuarios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracion_inicial_usuarios));
        
        string IMigrationMetadata.Id
        {
            get { return "201902051406450_migracion_inicial_usuarios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
