// <auto-generated />
namespace preguntados_ppodgaiz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class usuarios3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usuarios3));
        
        string IMigrationMetadata.Id
        {
            get { return "201902061504450_usuarios3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
