// <auto-generated />
namespace preguntados_ppodgaiz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class delete_Usuario_Add_Preguntas_Respondidas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_Usuario_Add_Preguntas_Respondidas));
        
        string IMigrationMetadata.Id
        {
            get { return "201902191424133_delete_Usuario_Add_Preguntas_Respondidas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
