// <auto-generated />
namespace preguntados_ppodgaiz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class log_eventos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(log_eventos));
        
        string IMigrationMetadata.Id
        {
            get { return "201902271414214_log_eventos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
