// <auto-generated />
namespace preguntados_ppodgaiz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class preguntas_y_respuestass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(preguntas_y_respuestass));
        
        string IMigrationMetadata.Id
        {
            get { return "201902081844375_preguntas_y_respuestass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
